### ISSUE TITLE
RFM69 radio does not send in beta0.9 v

### ISSUE THREAD

**Issue by wolass** [1technophile/OpenMQTTGateway#324]
I observed that the same code that works in the 0.8 does not work under 0.9 beta. 

The sending through RFM69 radio from the gateway based on Wemos D1 mini, does not work. However the receiving works in the 0.9.  

**To Reproduce**
1. load the standard code of the OMG on a Wemos D1 board
2. Connect to the WiFi and MQTT networks
3. publish anything on the home/OpenMQTTGateway/commands/MQTTtoRFM69 topic
4. Observe in the serial monitor thet OMG prepares json buffer.
4. Observe nothing on the other node. 

**Expected behavior**
I expected to see the sent data on a node set to promiscuous mode. Exactly that happens when I use 0.8 version. 

**Environment (please complete the following information):**
* OpenMQTTGateway version used (V0.9, master)
* Library downloaded through submodules. 
* For IR and RF clarify if you tested with the basic examples given with these libraries
* The receiving node is using a "struct_recieve" example from the RFM69 Library. 

NO COMPILATION ERRORS FOUND

**Comment by 1technophile** [comment]
Hello,

Supposing that you are using the same publishing (not json) Could you try to uncomment [simplepublishing](https://github.com/1technophile/OpenMQTTGateway/blob/ed44418a7f869d00bf770c3cce2687e43107e0db/User_config.h#L126) and see if it works for you?

**Comment by wolass** [comment]
Well, I can confirm that commenting out `simplepublishing` does not result in any change. Still no sending and still no "Data from JSON stored" message.

**Comment by 1technophile** [comment]
Thanks for pointing that.
Corrected in master

**Comment by 1technophile** [comment]
@wolass I close the issue, if it is still present don't hesitate to reopen it
