### ISSUE TITLE
Home Assistant Warning: "Template variable warning: 'dict object' has no attribute 'displaymetric' when rendering '{{ value_json.displaymetric }}'

### ISSUE THREAD

**Issue by Snuffy2** [1technophile/OpenMQTTGateway#1681]
**Describe the bug**
Since upgrading to v1.6.0, I've been getting a lot of these errors in my Home Assistant logs.

```
2023-06-11 21:33:44.109 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'displaymetric' when rendering '{{ value_json.displaymetric }}'
```
![SNAG-1946](https://github.com/1technophile/OpenMQTTGateway/assets/6526076/bbd63388-4f2a-4130-90e4-741cab6c321b)

I believe it is coming from OMG and may be related to #1504 although I believe that was added in v1.5.0 and seems to be [this line](https://github.com/1technophile/OpenMQTTGateway/blob/e27e055bf892a426c77cc2753d7e47724e27d70e/main/ZmqttDiscovery.ino#L511)

I'm running a Heltec WiFi LoRa 32 (V2.1) running RTL_433 which I believe uses the SSD1306 Display. I do have the display turned off.

![SNAG-1945](https://github.com/1technophile/OpenMQTTGateway/assets/6526076/6cb1bcbf-d308-44e9-b32a-eb31f5a2713f)

I do not recall seeing these errors in Home Assistant with OMG v1.5.1

**Environment (please complete the following information):**
* OpenMQTTGateway version used (V0.9.3, 0.8, development): 1.6
* Library version related to the problem you have (if you have troubles with RF provide the version of RCSwitch library)

**Comment by Snuffy2** [comment]
I turned on the Display to see if that had any effect and it didn't seem to change anything. The error is still appearing. Another thing I noticed is that displayMetric is not listed as an item in the SSD1306toMQTT JSON when looking with MQTT Explorer. It is listed under WebUItoMQTT and changes when I check/uncheck the Display Metric box in the WebUI.

<img width="1024" alt="2023-06-13_20-44-17 645" src="https://github.com/1technophile/OpenMQTTGateway/assets/6526076/8e5f0039-8592-4382-9c80-55550fb4b43f">

**Comment by DigiH** [comment]
This looks like a legacy discovery for displaymetric for SSD1306, from before it was moved to the WebUI. Needs to be removed for SSD1306/moved to WebUI.

**Comment by DigiH** [comment]
Hi @Snuffy2 

would you be able to verify with a test build?

**Comment by DigiH** [comment]
@Snuffy2 

A test build which should fix the warning messages can be installed at

https://docs.openmqttgateway.com/dev/upload/web-install.html

If you could also check the correct switching between metric and imperial units, that would be great.

**Comment by Snuffy2** [comment]
I installed version 9d8a96 this evening.

- [x] The Template variable warning is no longer showing
- [ ] I unchecked Display Metric in the WebUI. The change was shown in MQTT Explorer but the temperatures continue to show in °C
<img width="472" alt="2023-07-06_21-08-23 127" src="https://github.com/1technophile/OpenMQTTGateway/assets/6526076/d24a6152-c4e8-4458-9470-7b97064cb1da">
<img width="1024" alt="2023-07-06_21-01-07" src="https://github.com/1technophile/OpenMQTTGateway/assets/6526076/6d4f5dc7-f2c2-43c8-82a6-44033402bc41">

**Comment by DigiH** [comment]
Thanks for testing @Snuffy2 

The displayMetric setting only applies to the alternating device property unit display on the WebUI main page and on the Heltec/LilyGo internal OLED display.

The rtl_433 published MQTT messages will always have temperature_C, which can/should be auto converted to Fahrenheit if so defined in HA.

I was more curious as to whether the switching also works now in the HomeAssistant Gateway Control for the different display on the Heltec and WebUI.

**Comment by Snuffy2** [comment]
Gotcha. The temperature does show correctly in °F in the WebUI when I uncheck Display Metric.

**Comment by DigiH** [comment]
Thanks for the confirmations.

Closing
