### ISSUE TITLE
Cannot compile on Arduino 2.0.4 (for Sonoff RFBridge)

### ISSUE THREAD

**Issue by V1pr** [1technophile/OpenMQTTGateway#1584]
Hi,

tried to compile using Arduino 2.0.4 for my RFBridge, but bumped into 2 errors:

`error: declaration of 'T' shadows template parameter` at main.ino:290

Fixed it by removing the line breaks (these lines are the corrected ones):

```
template <typename T> void Config_update(JsonObject& data, const char* key, T& var);
template <typename T> void Config_update(JsonObject& data, const char* key, T& var) {
  if (data.containsKey(key)) {
```

`ENV_NAME undeclared` on main.ino:1858 , temp fixed it by adding the following lines around line 1835

```
#ifndef ENV_NAME
#define ENV_NAME "ESP8266"
#endif
```

The second is a quick&dirty fix, but these two fixes allowed me to compile 1.5.0 for my RFBridge-direct.

**Comment by eddieari** [comment]
Hello, 
thanks for the solution. The problem also occurs with a nodemcu. I have added your fix. But now, it remains with line by line 1806:
`error: unterminated #if
 1806 | #if defined(ESP8266) || defined(ESP32)
  exit status 1
Compilation error: unterminated #if`

Do you have an idea, how to solve?

THX

**Comment by V1pr** [comment]
> Hello, thanks for the solution. The problem also occurs with a nodemcu. I have added your fix. But now, it remains with line by line 1806: `error: unterminated #if 1806 | #if defined(ESP8266) || defined(ESP32) exit status 1 Compilation error: unterminated #if`
> 
> Do you have an idea, how to solve?
> 
> THX

@eddieari  I think you've made a copy paste error... line 1806 should look like only this (mind the missing first part!):

`#if defined(ESP8266) || defined(ESP32)`

So the `#if 1806 | ` is garbage...

**Comment by eddieari** [comment]
Thanks for the reply, but I think this is a wrong interpretation of my post. The code is part of the Ardurino IDE error message. I never had #if 1806 in the code. This is only part of the error message.
Here is the complete error message again:

 

> /Users/thomas/Downloads/OpenMQTTGateway-1.5.0/main/main.ino:1806: error: unterminated #if

 

> 1806 | #if defined(ESP8266) || defined(ESP32)

>   | 

> exit status 1

> Compilation error: unterminated #if

and here is the part I inserted in the code:
`#ifndef ENV_NAME
#define ENV_NAME "ESP8266"`

This is now line 1835 and 1836



Regards Thomas

**Comment by V1pr** [comment]
> Thanks for the reply, but I think this is a wrong interpretation of my post. The code is part of the Ardurino IDE error message. I never had #if 1806 in the code. This is only part of the error message. Here is the complete error message again:
> 
> > /Users/thomas/Downloads/OpenMQTTGateway-1.5.0/main/main.ino:1806: error: unterminated #if
> 
> > 1806 | #if defined(ESP8266) || defined(ESP32)
> 
> > |
> 
> > exit status 1
> 
> > Compilation error: unterminated #if
> 
> and here is the part I inserted in the code: `#ifndef ENV_NAME #define ENV_NAME "ESP8266"`
> 
> This is now line 1835 and 1836
> 
> Regards Thomas

@eddieari you're missing the line break after the first ENV_NAME
